### ISSUE TITLE
The components are presented without design at all

### ISSUE THREAD

**Issue by meirlamdan** [vuelessjs/vueless#205]
I installed the library
The components appear
But without any design

I get a warning about tailwind-merge
![image](https://github.com/user-attachments/assets/401ee96e-c384-46a9-b67d-ac24ac4fb531)

Is it maybe because the configuration of tailwind-merge is not compatible with the current version?

**Comment by itsJohnnyGrid** [comment]
Hi, @meirlamdan could you try to install the latest version of the packages and check if the issue still present:
* `npm i vueless@latest`
* `npm i @vueless/plugin-vite@latest`

And also provide more details about your environment / package manager etc.

And please check this alsо: https://docs.vueless.com/#minimal-requirements

**Comment by meirlamdan** [comment]
"@vueless/plugin-vite": "^0.0.71",
"vueless": "^0.0.424"
    
Operating System: Windows
IDE/Text Editor: Visual Studio Code (VSC)
Shell: Bash
Package Manager: npm

**Comment by meirlamdan** [comment]
Okay
Apparently this is a problem with tailwind-merge
https://github.com/dcastil/tailwind-merge/issues/481

**Comment by meirlamdan** [comment]
The mistake was that I left the default setting 
in tailwind.config.js
```  
content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ], theme: {
    extend: {},
  },
  ```
Maybe it should be highlighted in the documents

**Comment by itsJohnnyGrid** [comment]
@meirlamdan I guess you forgot to add `vuelessPreset` into your `tailwind.config.js`. See [step 3 in the docs here](https://docs.vueless.com/). This config already set there to make the configuration more easier.

If the issue persists after that, please let us know.

**Comment by meirlamdan** [comment]
I set it right
But I also left the section below
```
content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ], theme: {
    extend: {},
  },
  ```

**Comment by itsJohnnyGrid** [comment]
> I set it right But I also left the section below
> 
> ```
> content: [
>     "./index.html",
>     "./src/**/*.{vue,js,ts,jsx,tsx}",
>   ], theme: {
>     extend: {},
>   },
> ```

Could you share the full file of your `tailwind.config` file please.

**Comment by meirlamdan** [comment]
```js
/** @type {import('tailwindcss').Config} */
import { vuelessPreset } from "vueless/preset.tailwind.js";

export default {
  presets: [vuelessPreset],
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ]
}

```

**Comment by itsJohnnyGrid** [comment]
@meirlamdan I'll double check this and let you know, thanks. By default it should work without content config property.
