### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by meirlamdan** [vuelessjs/vueless#207]
What about rtl support?

![image](https://github.com/user-attachments/assets/ee030a46-469d-4766-a816-ce1936c2929d)

**Comment by itsJohnnyGrid** [comment]
@meirlamdan it's funny that I thought that it's quit low requested feature and here is the issue, thank you for it :)

I added this feature to our internal roadmap but the feature is in low priority now.

As a workaround I suggest to use `config` prop or global config file `vueless.config.js` to implement this. See [the docs here](https://docs.vueless.com/customization/components).
